const Router = require('express')
const bookingController = require('../controllers/bookingController')
const adminsController = require('../controllers/adminsController')
const reviewController = require('../controllers/reviewController')
const auth = require('../middleware/auth')
const galleryController = require('../controllers/galleryController')
const router = new Router()

router.post('/', bookingController.addOrder)
router.post('/orders', bookingController.getOrders)
router.post('/allorders', bookingController.getAllOrders)
router.post('/changeDesc', bookingController.changeDesc)
router.post('/delOrder', bookingController.delOrder)
router.post('/reg', adminsController.reg)
router.post('/log', adminsController.log)
router.post('/addReview', reviewController.addReview)
router.get('/getReviews', reviewController.getReviews)
router.get('/getAdminReviews', auth, reviewController.getAdminReviews)
router.post('/changeStatusReview', auth, reviewController.changeStatusReview)
router.post('/gallery/addImage', auth, galleryController.addImage)
router.get('/gallery/getImages', galleryController.getImages)
router.get('/gallery/getImage', galleryController.getImage)
router.get('/gallery/getAdminImages', auth, galleryController.getAdminImages)
router.post('/gallery/delImage', auth, galleryController.delImage)
router.post('/gallery/changeImage', auth, galleryController.changeImage)
router.post('/orderPhone', adminsController.orderPhone)

module.exports = router